name: "Merge Queuing / PreCheck"
description: "Support for merge queuing"
author: "yamachu"
inputs:
  required-codeowners:
    description: "Trigger user must be a codeowner"
    required: false
    default: "true"
outputs:
  base-branch:
    description: "Name of the base branch"
    value: ${{ steps.get_base_branch.outputs.result }}

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      id: get_base_branch
      with:
        script: |
          const { default: isMergeable } = await import('${{ github.action_path }}/../src/isMergeable.js')
          return await isMergeable({ github }, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          })
    - uses: actions/github-script@v7
      with:
        script: |
          const { default: postPreActionUrl } = await import('${{ github.action_path }}/../src/postPreActionUrl.js')
          await postPreActionUrl({ github }, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            runId: context.runId
          })
    - uses: actions/github-script@v7
      with:
        script: |
          if (${{ inputs.required-codeowners }} === false) {
            return
          }
          const { default: isCODEOWNERS } = await import('${{ github.action_path }}/../src/isCODEOWNERS.js')
          await isCODEOWNERS({ github }, {
            owner: context.repo.owner,
            repo: context.repo.repo,
            actor: context.triggering_actor || context.actor,
          })
